apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata: 
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: reda7892/postgres:latest
        env:
        - name: POSTGRES_USER
          value: reda 
        - name: POSTGRES_PASSWORD
          value: rourou
        - name: POSTGRES_DB
          value: bd  

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
